name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure cargo
      run: |
        export RUSTFLAGS="-D warnings"
        export RUSTDOCFLAGS="-D warnings"
    - name: Clippy
      run: |
        rustup component add clippy
        cargo clippy --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Documentation
      run: cargo doc --verbose
